version: '3'

networks:
  yandex_backend_network:

services:
  nginx:
    networks:
      - yandex_backend_network
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app
      - db

  app:
    networks:
      - yandex_backend_network
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    expose:
      - 8080
    environment:
      DB_HOST: db

  db:
    networks:
      - yandex_backend_network
    container_name: db
    volumes:
      - data_db_yandex_vlm:/var/lib/postgresql/data
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  data_db_yandex_vlm: