version: '3'

networks:
  yandex_backend_utils_network:

services:
  db:
    container_name: db_util
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"