create table shop_unit
(
    id        uuid         not null
        constraint shop_unit_pkey
            primary key,
    date      timestamp,
    name      varchar(255) not null,
    price     bigint,
    type      varchar(255) not null,
    parent_id uuid
        constraint fkl2nx2b5fsamdqyir6lif6n7as
            references shop_unit
            on delete cascade
);

create table shop_unit_history
(
    id        bigint generated by default as identity (maxvalue 2147483647)
        constraint shop_unit_history_pkey
            primary key,
    date      timestamp,
    name      varchar(255) not null,
    origin_id uuid
        constraint shop_unit_history_shop_unit_id_fk
            references shop_unit
            on delete cascade,
    price     bigint,
    type      varchar(255) not null,
    parent_id uuid
);
